version: '3.4'

services:
  employeewebservice:
    image: employeewebservice:dev
    container_name: EmployeeWebService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "EmployeeWebService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_employeewebservice$
    volumes:
      - C:\Users\Mikhail\source\repos\EmployeeWebService\EmployeeWebService:/app
      - C:\Users\Mikhail\source\repos\EmployeeWebService:/src
      - C:\Users\Mikhail\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_employeewebservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_employeewebservice$ \"/app/bin/Debug/netcoreapp3.1/EmployeeWebService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true